version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: "User"
      POSTGRES_PASSWORD: "11"
      POSTGRES_DB: "PostgreSQL"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data:
